const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: './backend/.env' });

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing Supabase credentials in .env');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function createNotificationsTable() {
    console.log('Attempting to create notifications table via SQL RPC or checking existence...');

    // Note: Standard supabase-js client cannot execute raw DDL (CREATE TABLE) unless there is a specific RPC function set up for it.
    // However, we will try to assume the user might have to run this in their SQL editor if this fails.
    // For now, I'll print the SQL to be run.

    const sql = `
    CREATE TABLE IF NOT EXISTS notifications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        recipient_phone VARCHAR(20),
        recipient_name VARCHAR(100),
        message_body TEXT,
        notification_type VARCHAR(50) DEFAULT 'WHATSAPP',
        status VARCHAR(20) DEFAULT 'SENT',
        related_entity_type VARCHAR(50), 
        related_entity_id VARCHAR(50),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    `;

    console.log('\n--- PLEASE RUN THIS SQL IN YOUR SUPABASE SQL EDITOR ---\n');
    console.log(sql);
    console.log('\n-----------------------------------------------------\n');

    // Attempting a simple query to see if connection works
    const { data, error } = await supabase.from('states').select('count', { count: 'exact', head: true });

    if (error) {
        console.error('Connection check failed:', error.message);
    } else {
        console.log('Supabase connection successful. Please ensure the table is created.');
    }
}

createNotificationsTable();
