const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = createClient(supabaseUrl, supabaseKey, {
    auth: {
        autoRefreshToken: false,
        persistSession: false
    }
});

async function revertImplementingAgencies() {
    try {
        console.log('╔═══════════════════════════════════════════════════════════════════════╗');
        console.log('║  REVERTING IMPLEMENTING AGENCIES TABLE                                ║');
        console.log('╚═══════════════════════════════════════════════════════════════════════╝\n');

        // Step 1: Show current state
        console.log('📊 Current State:\n');
        const { data: currentAgencies } = await supabase
            .from('implementing_agencies')
            .select('*')
            .order('state_id')
            .order('id');

        console.log(`Total agencies: ${currentAgencies.length}`);

        const byState = {};
        currentAgencies.forEach(a => {
            if (!byState[a.state_id]) byState[a.state_id] = [];
            byState[a.state_id].push(a);
        });

        console.log(`States represented: ${Object.keys(byState).length}\n`);

        // Step 2: Identify agencies created by our scripts (with auto-generated names)
        const autoGeneratedAgencies = currentAgencies.filter(a =>
            a.agency_name && a.agency_name.match(/^IA \d+ - /)
        );

        const originalAgencies = currentAgencies.filter(a =>
            !a.agency_name || !a.agency_name.match(/^IA \d+ - /)
        );

        console.log('📋 Analysis:\n');
        console.log(`  Auto-generated agencies (created by scripts): ${autoGeneratedAgencies.length}`);
        console.log(`  Original agencies (pre-existing): ${originalAgencies.length}\n`);

        if (autoGeneratedAgencies.length === 0) {
            console.log('✓ No auto-generated agencies found. Database appears to be in original state.\n');
            return;
        }

        // Step 3: Show what will be deleted
        console.log('🗑️  Agencies to be deleted:\n');
        console.log('='.repeat(80));

        autoGeneratedAgencies.forEach(a => {
            console.log(`  ✗ ${a.agency_name} (${a.email || 'no email'})`);
        });

        console.log('='.repeat(80));
        console.log(`\nTotal to delete: ${autoGeneratedAgencies.length}\n`);

        // Step 4: Delete user accounts first
        console.log('👤 Deleting associated user accounts...\n');

        let usersDeleted = 0;
        for (const agency of autoGeneratedAgencies) {
            if (agency.user_id) {
                const { error } = await supabase.auth.admin.deleteUser(agency.user_id);
                if (error) {
                    console.log(`  ⚠ Failed to delete user for ${agency.agency_name}: ${error.message}`);
                } else {
                    console.log(`  ✓ Deleted user for ${agency.agency_name}`);
                    usersDeleted++;
                }
            }
        }

        console.log(`\n  Deleted ${usersDeleted} user accounts\n`);

        // Step 5: Delete the agencies
        console.log('🗑️  Deleting auto-generated agencies...\n');

        const idsToDelete = autoGeneratedAgencies.map(a => a.id);

        const { error: deleteError } = await supabase
            .from('implementing_agencies')
            .delete()
            .in('id', idsToDelete);

        if (deleteError) {
            console.error('✗ Error deleting agencies:', deleteError);
            return;
        }

        console.log(`✓ Successfully deleted ${idsToDelete.length} agencies\n`);

        // Step 6: Verify final state
        console.log('✅ Verification:\n');

        const { data: finalAgencies } = await supabase
            .from('implementing_agencies')
            .select('*');

        const finalByState = {};
        finalAgencies.forEach(a => {
            if (!finalByState[a.state_id]) finalByState[a.state_id] = [];
            finalByState[a.state_id].push(a);
        });

        console.log('='.repeat(80));
        console.log(`Total agencies remaining: ${finalAgencies.length}`);
        console.log(`States represented: ${Object.keys(finalByState).length}`);

        let statesWith2 = 0, statesWithMore = 0, statesWithLess = 0;
        for (const sid in finalByState) {
            const count = finalByState[sid].length;
            if (count === 2) statesWith2++;
            else if (count > 2) statesWithMore++;
            else statesWithLess++;
        }

        console.log(`States with exactly 2 agencies: ${statesWith2}`);
        console.log(`States with more than 2: ${statesWithMore}`);
        console.log(`States with less than 2: ${statesWithLess}`);
        console.log('='.repeat(80));

        console.log('\n╔═══════════════════════════════════════════════════════════════════════╗');
        console.log('║  ✅ REVERT COMPLETE                                                   ║');
        console.log('║  Database has been restored to original state                         ║');
        console.log('╚═══════════════════════════════════════════════════════════════════════╝\n');

    } catch (error) {
        console.error('Unexpected error:', error);
    }
}

revertImplementingAgencies();
