-- 1. Create table for District -> Agency Releases (Missing Table)
CREATE TABLE IF NOT EXISTS agency_fund_releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id UUID REFERENCES districts(id),
    agency_id UUID REFERENCES implementing_agencies(id),
    component TEXT[] DEFAULT '{}',
    amount_cr NUMERIC(20, 2),
    amount_rupees NUMERIC(20, 2),
    release_date DATE,
    remarks TEXT,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create table for State -> Agency Fund Releases
-- Dropping table if it exists to ensure type change applies if partially created
DROP TABLE IF EXISTS state_agency_fund_releases;

CREATE TABLE state_agency_fund_releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id INTEGER REFERENCES states(id), -- Changed from UUID to INTEGER
    agency_id UUID REFERENCES implementing_agencies(id),
    component TEXT[] DEFAULT '{}',
    amount_cr NUMERIC(20, 2),
    amount_rupees NUMERIC(20, 2),
    release_date DATE,
    sanction_order_no TEXT,
    remarks TEXT,
    created_by TEXT, -- User ID or Name
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Fix/Ensure relationships (Idempotent)

-- Fix relationships for agency_fund_releases
-- We verify/re-add constraints to be safe
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agency_fund_releases_agency_id_fkey') THEN
        ALTER TABLE agency_fund_releases
        ADD CONSTRAINT agency_fund_releases_agency_id_fkey 
        FOREIGN KEY (agency_id) 
        REFERENCES implementing_agencies(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agency_fund_releases_districts_id_fkey') THEN
        ALTER TABLE agency_fund_releases
        ADD CONSTRAINT agency_fund_releases_districts_id_fkey 
        FOREIGN KEY (district_id) 
        REFERENCES districts(id);
    END IF;
END $$;


-- 4. Enable RLS (Optional)
ALTER TABLE agency_fund_releases ENABLE ROW LEVEL SECURITY;
ALTER TABLE state_agency_fund_releases ENABLE ROW LEVEL SECURITY;

-- Policies for agency_fund_releases
DROP POLICY IF EXISTS "Enable read access for all users" ON agency_fund_releases;
CREATE POLICY "Enable read access for all users" ON agency_fund_releases
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for authenticated users" ON agency_fund_releases;
CREATE POLICY "Enable insert access for authenticated users" ON agency_fund_releases
    FOR INSERT WITH CHECK (true);

-- Policies for state_agency_fund_releases
DROP POLICY IF EXISTS "Enable read access for all users" ON state_agency_fund_releases;
CREATE POLICY "Enable read access for all users" ON state_agency_fund_releases
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for authenticated users" ON state_agency_fund_releases;
CREATE POLICY "Enable insert access for authenticated users" ON state_agency_fund_releases
    FOR INSERT WITH CHECK (true);
