-- Create the master table for implementing agencies
CREATE TABLE IF NOT EXISTS implementing_agencies (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE implementing_agencies ENABLE ROW LEVEL SECURITY;

-- Policy to allow read access to everyone
CREATE POLICY "Allow public read access" ON implementing_agencies
    FOR SELECT USING (true);

-- Insert the master list of agencies
INSERT INTO implementing_agencies (name) VALUES
('Ministry of Tribal Affairs'),
('Tribal Cooperative Marketing Development Federation of India (TRIFED)'),
('National Scheduled Castes Finance and Development Corporation (NSFDC)'),
('National Backward Classes Finance & Development Corporation (NBCFDC)'),
('Ministry of Social Justice and Empowerment'),
('State Social Welfare Department'),
('District Collector / District Magistrate'),
('State Scheduled Castes Development Corporation'),
('State Scheduled Tribes Development Corporation'),
('Rural Development Department'),
('Public Sector Undertakings (PSUs)'),
('State Nodal Agency (SNA)'),
('National Minorities Development & Finance Corporation (NMDFC)'),
('State Women Development Corporation'),
('Skill Development Mission'),
('Urban Development Department'),
('National Handicapped Finance and Development Corporation (NHFDC)'),
('SNAs under PM-AJAY'),
('Agriculture Department'),
('Education Department'),
('Labour Department'),
('Welfare Boards'),
('Micro Finance Institutions'),
('State Rural Livelihood Mission (SRLM)'),
('Block Development Officer (BDO)'),
('Municipal Corporations / Municipalities'),
('NGOs registered under NITI Aayog Darpan'),
('Technical Institutions (IITs/NITs/Polytechnics)'),
('Project Implementation Agencies (PIAs)'),
('Central Social Welfare Board'),
('District Tribal Welfare Officer'),
('State Tribal Research Institute'),
('Public Works Department (PWD)'),
('State Health Department'),
('State Education Department'),
('State Animal Husbandry Department'),
('Transport Department'),
('Energy Department'),
('Water Resources Department'),
('District Panchayat / Zilla Parishad'),
('Community Based Organizations (CBOs)'),
('State Fisheries Department'),
('State Environment Department'),
('State Employment Exchange'),
('Youth Welfare Department'),
('National Public Cooperation and Child Development (NIPCCD)'),
('Skill India Mission Partners'),
('Digital India Corporation'),
('Electronics Corporation of India Limited (ECIL)'),
('National Institute of Rural Development (NIRD)'),
('State Skill Development Missions'),
('Local Self Government Institutions (LSGIs)'),
('Central Warehousing Corporation'),
('State Planning Commission'),
('Major Port Trusts'),
('State Road Transport Corporations'),
('State Power Distribution Companies (DISCOMs)'),
('State Urban Livelihood Mission (SULM)'),
('Agricultural Technology Management Agency (ATMA)'),
('Central Food Technological Research Institute (CFTRI)'),
('State Forest Department'),
('State Tourism Department'),
('District Agriculture Officer'),
('State Horticulture Mission'),
('State Trading Corporation'),
('State Cooperative Banks'),
('National Small Industries Corporation (NSIC)'),
('National Housing Bank'),
('State Marketing Boards'),
('State Export Corporations'),
('State Audit Department'),
('State Legal Services Authority'),
('District Rural Development Agency (DRDA)'),
('State Food & Civil Supplies Corporation'),
('State Textile Corporation'),
('District Health Society'),
('State Power Generation Corporation'),
('Central Pollution Control Board'),
('State Disaster Management Authority'),
('Public Health Engineering Department (PHED)'),
('National Seeds Corporation'),
('Rural Electrification Corporation (REC)'),
('Central Soil Salinity Research Institute'),
('State Social Security Board'),
('National Film Development Corporation'),
('State MSME Department'),
('State Science & Technology Council'),
('State Transport Department'),
('District Education Officer'),
('State Women Commission')
ON CONFLICT (name) DO NOTHING;
