-- Create district_assignment table
create table if not exists district_assignment (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  admin_name text not null,
  district_name text not null,
  phone_no text not null,
  email text not null,
  username text,
  password text,
  bank_account_number text,
  status text default 'Active'
);

-- Add unique constraint on email and username
alter table district_assignment add constraint district_assignment_email_key unique (email);
alter table district_assignment add constraint district_assignment_username_key unique (username);

-- Enable RLS
alter table district_assignment enable row level security;

-- Create policy to allow all access (for development)
create policy "Enable all access for all users" on district_assignment for all using (true) with check (true);
